### ISSUE TITLE
org-clock-convenience-goto-ts should be bound to RET in org-agenda-mode

### ISSUE THREAD

**Issue by clange** [dfeich/org-clock-convenience#1]
First of all, thank you very much for org-clock-convenience! I am also tracking every minute of my work and have been looking for this for a long time.

Here's a partial suggestion for improvement: When I'm on a log line in an agenda view I'd like RET not to jump to the headline of the respective task, but to the precise clock entry.

As the latter does not yet work well with folding (it doesn't make the headline visible when it's been folded away – this might be reported as a separate issue here), I restricted this behaviour to work on the actual timestamps only.

Please find my code at https://github.com/clange/emacs/blob/master/.emacs.d/init/org-clock.el#L63 (the function) and https://github.com/clange/emacs/blob/master/.emacs.d/init/org-clock.el#L86 (the keybinding).

**Comment by dfeich** [comment]
Hi Christoph

Glad that this is useful to others.

The functionality you describe actually was the default behavior of the unmodified org-mode for a long time. You went to the log line, pressed RET and ended up at the particular clock line. I always used this to edit particular clock values.

At some point this did not work any more, the reason being that the item's clock drawer (I always use clock drawers) was not opened when jumping to the org file from the agenda. I could see that the cursor was jumping to the correct position, but it was hidden in the drawer, and moving the cursor/opening the drawer lost the cursor position.

I fixed this using the following snippet in my init file and invoking it in the `org-agenda-after-show-hook`:

``` emacs-lisp
;; when jumping to the agenda from a log message, the point ends up at
;; a CLOCK item in a LOGBOOK drawer, but the drawer gets closed, even
;; if the drawer was open before. I add a drawer opening function to
;; the respective agenda hook
(defun dfeich/org-open-if-in-drawer ()
  (let ((element (org-element-at-point)))
    (while (and element
        (not (memq (org-element-type element)
               '(drawer property-drawer))))
      (setq element (org-element-property :parent element)))
    (when element
      (let ((pos (point)))
    (goto-char (org-element-property :begin element))
    (org-flag-drawer nil)
    (goto-char pos)))))

(add-hook 'org-agenda-after-show-hook #'dfeich/org-open-if-in-drawer)
```

I think this should fix the whole situation. I can jump from anywhere in a clock log line to the respective clock line in the source file. I think I actually should have submitted that as a patch to org, but somehow I forgot. Since it only requires standard org-mode functions it probably will be the preferred solution for a patch.

Cheers,
Derek

**Comment by clange** [comment]
Derek, thank you very much for your quick response; I appreciate!

> The functionality you describe actually was the default behavior of the unmodified org-mode for a long time. You went to the log line, pressed RET and ended up at the particular clock line.

Indeed, now that you said it, I think I remember.

> I think this should fix the whole situation.

Thank you very much, tested and confirmed :-)

> I think I actually should have submitted that as a patch to org

I agree that this would certainly be highly welcome.
