### ISSUE TITLE
use-package does not work

### ISSUE THREAD

**Issue by YujiShen** [dfeich/org-clock-convenience#11]
`use-package` does not work for me, but alternative method works. Any idea why it does not work? Here is my config, I try to bind keys and override regex.

```elisp
  (use-package org-clock-convenience
    :ensure t
    :bind (:map org-agenda-mode-map
      ("<S-up>" . org-clock-convenience-timestamp-up)
      ("<S-down>" . org-clock-convenience-timestamp-down))
    :init
    (setq org-clock-convenience-clocked-agenda-re "^ +Clocked:[[:space:]]+\\(([0-9]+:[0-5][0-9])\\|(-)\\)[[:space:]]*|[[:space:]]*\\(\\([ \t012][0-9]\\):\\([0-5][0-9]\\)\\)\\(?:-\\(\\([ 012][0-9]\\):\\([0-5][0-9]\\)\\)\\|.*\\)?[[:space:]]?|[[:space:]]*\\([^ ]+\\)[[:space:]]*|"
          org-clock-convenience-clocked-agenda-fields '(duration d1-time d1-hours d1-minutes d2-time d2-hours d2-minutes filename)
    )
  )
```

**Comment by dfeich** [comment]
Hi,

You need to find out whether it is just something with the key mapping going wrong, e.g. it getting overridden by some other mapping for those keys, or whether the "does not work" has to do with your changing the regexps. Since you write that configuring it differently works for you, I suspect that it just has to do with the key mappings.

Go into your agenda buffer to check which functions are bound to the keys. Inside of the active buffer, do  "C-h k" (invokes the describe-key command) + the key combination, in this case  "<S-down>". This will display what command is bound in the current context to this key combination. Once you know the command that is probably overlaying the org-clock-convenience command you wanted to set in the use-package, you can try to understand where in your configuration that may happen.

**Comment by YujiShen** [comment]
Thanks @dfeich! This is very helpful.

I found it is bound to `(org-agenda-priority-up)`. I did not define this in my init file. Maybe it is defined by Spacemacs. But I don't know why it is not overrode by my config here...
