### ISSUE TITLE
Documentation enhancements: configuration and use

### ISSUE THREAD

**Issue by heikkil** [dfeich/org-clock-convenience#2]
Thanks for nifty functions. Here some ways I started using them. Feel free to include somewhere in the documentation for other to use.

# Installation

use-package makes installation and configuration easy:

    (use-package org-clock-convenience
      :ensure t
      :defer t
      :bind (:map org-agenda-mode-map
                  ("<S-up>" . org-clock-convenience-timestamp-up)
                  ("<S-down>" . org-clock-convenience-timestamp-down)
                  ("'" . org-clock-convenience-fill-gap)))
    
# Use
An entry for org-capture-templates that prompts for a tag, adds timestamp and category that is displayed in org agenda, and starts the clock:

         ("w" "work" entry (file+datetree "~/Dropbox/org/work.org")
              "* %? %^g\n     :PROPERTIES:\n     :CREATED:  %U\n     :CATEGORY: work\n     :END:\n%i"
              :clock-in t :clock-keep t)

**Comment by dfeich** [comment]
Thanks for the suggestion. I added the use-package configuration I have been using in my own config. Maybe it's a good to always include the use-package stanzas as well, since nowadays use-package has become a de-facto standard for many.

I think your capture template proposal is nice, but quite specific to your workflow, so I guess it is better suited for a blog post instead of the documentation of this particular package.

Thanks,
Derek
